import React, { useState } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";

import { CardBack, Form, CardFront, Thankyou } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  interface FormValues {
    cardName?: string;
    cardNumber?: string;
    month?: string;
    year?: string;
    cvc?: string;
  }

  const [cardDetails, setCardDetails] = useState<FormValues>({
    cardName: "",
    year: "",
    month: "",
    cvc: "",
    cardNumber: "",
  });

  const [validForm, setValidForm] = useState(false);


  const { cardName, cardNumber, month, year, cvc } = cardDetails;
  cardDetails.cardNumber = cardNumber ? cardNumber.replace(/(.{4})/g, "$1\t") : undefined;
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex flex-col sm:flex-row justify-center items-center overflow-hidden">
        <div className="bg-bgImgMobile sm:bg-bgImgDesktop w-full h-6 basis-1/3 sm:h-screen mb-12 sm:mb-0">
          <div className="relative translate-y-28 translate-x-4 z-40 sm:translate-y-36 md:translate-x-1/4">
            <CardFront
              cardName={cardName}
              cardNumber={cardNumber}
              year={year}
              month={month}
            />
          </div>
          <div className="relative -translate-y-[7.15rem] translate-x-16 z-0 sm:translate-y-48 sm:translate-x-[15%] md:translate-x-1/3">
            <CardBack cvc={cvc} />
          </div>
        </div>

        <div className="flex basis-2/3 justify-center mt-11 ">
          {validForm ? (
            <Thankyou setValidForm={setValidForm} />
          ) : (
            <Form setCardDetails={setCardDetails} setValidForm={setValidForm} />
          )}
        </div>
      </main>
    </>
  );
}
